###############################################################
### Please rewrite below values to adjust your environment. ###
###############################################################
plugins:
  - vagrant-reload
guestuser: vagrant
mount:
  - ${HOME}/git
  - ${HOME}/.aws
vb:
  memory: 4096
  cpus: 2
  gui: true
vscode:
  code-settings-sync: ''
